# Generated by Django 5.1 on 2024-09-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='categoria',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
