# Generated by Django 5.1 on 2024-09-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='updated_at',
            new_name='fecha_ingreso',
        ),
    ]
