# Generated by Django 5.1 on 2024-09-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_rename_updated_at_registro_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='categoria',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
    ]
